In [46]:
##all steps for machine learning

In [ ]:
##import data

In [1]:
from sklearn.datasets import load_iris

In [3]:
d = load_iris()

In [6]:
d.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [21]:
##print(d.DESCR)

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame(d.data,columns=d.feature_names)

In [11]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [12]:
d.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
d.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [16]:
df['target'] = d.target

In [17]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [18]:
df.shape

(150, 5)

In [19]:
##split dataset

In [20]:
from sklearn.model_selection import train_test_split

/home/piyush/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [23]:
X_train,X_test,y_train,y_test = train_test_split(d.data, d.target, test_size=0.2)

In [24]:
X_train.shape

(120, 4)

In [25]:
X_test.shape

(30, 4)

In [27]:
##train model

In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
knn = KNeighborsClassifier()

In [33]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [34]:
##prediction

In [35]:
pred = knn.predict(X_test)

In [36]:
pred

array([0, 2, 0, 0, 0, 1, 0, 1, 0, 2, 0, 1, 0, 1, 0, 0, 1, 0, 2, 1, 0, 2,
       1, 1, 2, 2, 2, 2, 2, 2])

In [37]:
y_test

array([0, 2, 0, 0, 0, 1, 0, 1, 0, 2, 0, 1, 0, 1, 0, 0, 1, 0, 2, 1, 0, 2,
       1, 1, 1, 1, 2, 1, 2, 2])

In [38]:
##Evaluation

In [39]:
from sklearn.metrics import accuracy_score

In [41]:
accuracy_score(y_test,pred)

0.9

In [42]:
import numpy as np

In [45]:
np.where(y_test!=pred)

(array([24, 25, 27]),)